### ISSUE TITLE
error from loading resources: interaction_misc

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#130] opened 2020-02-07 17:25 UTC
**Describe the bug**
can not load interaction_misc

**To Reproduce**
0. import pypath.resources.network as network_resources
1. pa=main.PyPath()
2. pa.load_resources(network_resources.interaction_misc,exclude=exc_name)

**Desktop (please complete the following information):**
- Python version: 3.6.7
- PyPath: 0.9.6

**Additional context**
>>> pa.load_resources(network_resources.interaction_misc,exclude=exc_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/main.py", line 6592, in load_resources
    keep_raw = keep_raw,
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/main.py", line 6662, in load_resource
    keep_raw = keep_raw,
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/main.py", line 2753, in _read_network_data
    for lnum, line in enumerate(infile):
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/dataio.py", line 8004, in hi_iii
    for row in c.result:
TypeError: 'NoneType' object is not iterable

** additional information **
maybe the above is due to my exclusion?
exc_name=['ELM','LMPID','phosphoELM','SignaLink2','SignaLink3','NRF2ome','ARN','HPRD-phos','HPRD','ACSN','Wang','BioCarta','Li2012','InnateDB','DEPOD','PhosphoPoint','PhosphoSite','SPIKE','NCI-PID','CPDB','KEGG','PathwayCommons','Laudanna-effects','Laudanna-directions','HPMR','Kirouac2010','PhosphoNetworks','MIMP','TransmiR','miRecords','miRTarBase','IntOGen','ProtMapper']

** Thank You! **

**Comment by deeenes** [comment] 2020-02-10 18:06
Hi Lu,

This I could not reproduce, the `pypath.inputs.main.hi_iii()` works for me fine.
Maybe a temporary server or network problem? Or something was wrong still in `0.9.6`.
However I found some issues related to the new module structure in pypath `0.10.0`, hopefully I fixed most of them.

Best,

Denes

**Comment by deeenes** [comment] 2020-02-11 20:29
Now fixed some more issues (name of methods for Lit-BM datasets, imports in the hippie module), and I can run your code with no error:

```
from pypath.legacy import main
import pypath.resources.network as network_resources

exc_name=['ELM','LMPID','phosphoELM','SignaLink2','SignaLink3','NRF2ome','ARN','HPRD-phos','HPRD','ACSN','Wang','BioCarta','Li2012','InnateDB','DEPOD','PhosphoPoint','PhosphoSite','SPIKE','NCI-PID','CPDB','KEGG','PathwayCommons','Laudanna-effects','Laudanna-directions','HPMR','Kirouac2010','PhosphoNetworks','MIMP','TransmiR','miRecords','miRTarBase','IntOGen','ProtMapper']

pa=main.PyPath()
pa.load_resources(network_resources.interaction_misc,exclude=exc_name)
```

Closing this for now and please re-open or create a new one if you are still experiencing issues.

**Closed by deeenes** 2020-02-11 20:29 UTC
Labels: bug
