### ISSUE TITLE
problem with pypath

### ISSUE THREAD

**Issue by jeremyEudaric** [saezlab/pypath#173] opened 2021-04-09 10:55 UTC
Hi all,
l have a problem with pypath it's new for me , l wante to see the interactions and the dataframe but l have these errors a little bit strange 
![Capture](https://user-images.githubusercontent.com/79277563/114170174-d2dc4e80-9932-11eb-8aab-85f44502e5bb.PNG)

Thks in advance

**Comment by deeenes** [comment] 2021-04-09 11:55
Hi,

These methods load one resource after another, and if is any error happens at one of the resources, you see such a message. If you check the log file there should be a traceback above this message. You can find the log file:

```
import pypath
pypath._session_mod.session.log.fname
```

Also you can see the error by calling directly the input method, and use this to check if the error persists:

```
from pypath.inputs import cellchatdb
i = cellchatdb.cellchatdb_interactions()
```

For me this run just fine, I couldn't reproduce any error. The errors are most often due to failed downloads. You could try to delete the potentially corrupted cache file and call the input method again. The cache file should be `~/.pypath/cache/07d4a4294f8a0954cf44ae572db94980-CellChatDB.human.rda`. Note, to process CellChatDB the `rdata` package is required.

Best,

Denes

**Comment by deeenes** [comment] 2021-04-09 11:58
I forgot to add, even if some of the resources fail to load, you have the network built from the successfully loaded resources. If you want a data frame, that's in `n.df` (or call `n.make_df()` to create it).

**Comment by jeremyEudaric** [comment] 2021-04-09 13:01
hi 
Thank you fo you help 
When l do
 from pypath.inputs import cellchatdb
i = cellchatdb.cellchatdb_interactions()

l have an error TypeError: 'RObject' object is not iterable

l trye with an other method 
from pypath.legacy import main

l hav an error No module `cairo` available.
Some plotting functionalities won't be accessible. No module named 'igraph.compat'

l can not undertand beacuse l want only see the dataframe like this 
![Capture](https://user-images.githubusercontent.com/79277563/114183842-65d1b480-9944-11eb-87d6-5166b600a792.PNG)

thanks your help

**Comment by deeenes** [comment] 2021-04-09 13:26
> hi
> Thank you fo you help
> When l do
> from pypath.inputs import cellchatdb
> i = cellchatdb.cellchatdb_interactions()
> 
> l have an error TypeError: 'RObject' object is not iterable

It would be very helpful to see the full traceback. Also I am wondering if you tried to remove the cache file? Before removing it, maybe you can check its integrity:

```
md5sum ~/.pypath/cache/07d4a4294f8a0954cf44ae572db94980-CellChatDB.human.rda
# 153ba31111d5586dfa42fb938cf15713
```

> 
> l trye with an other method
> from pypath.legacy import main
> 
> l hav an error No module `cairo` available.
> Some plotting functionalities won't be accessible. No module named 'igraph.compat'

These messages about cairo are not relevant. However, the legacy module uses the same input methods, and your issue is in one of those input methods, `pypath.inputs.cellchatdb`. I am wondering what happens if you try to open the file with `rdata`:

```
import rdata
path = '~/.pypath/cache/07d4a4294f8a0954cf44ae572db94980-CellChatDB.human.rda'
rda = rdata.parser.parse_file(path)
rda_conv = rdata.conversion.convert(rda)['CellChatDB.human']
list(rda_conv.items())[0]
```

> 
> l can not undertand beacuse l want only see the dataframe like this
> ![Capture](https://user-images.githubusercontent.com/79277563/114183842-65d1b480-9944-11eb-87d6-5166b600a792.PNG)
> 
> thanks your help

You can have the data frame, you will only miss CellChatDB, all the other network resources will be included:

```
from pypath.core import network
from pypath.resources import network as netres
n = network.Network(netres.pathway, make_df = True)
n.df
```

**Comment by jeremyEudaric** [comment] 2021-04-09 13:42
Thank you for your time ;)
 if l try to open the file with raw data l have yhis error :

[Errno 2] No such file or directory: '~/.pypath/cache/07d4a4294f8a0954cf44ae572db94980-CellChatDB.human.rda'

l will remove CellChatDB l think

At the end the aim of my work will be to see all  the OmniPath  database ( withe the interations in a dataframe) how l can do that?

thank in advance

**Comment by deeenes** [comment] 2021-04-09 15:04
> Thank you for your time ;)
> if l try to open the file with raw data l have yhis error :
> 
> [Errno 2] No such file or directory: '~/.pypath/cache/07d4a4294f8a0954cf44ae572db94980-CellChatDB.human.rda'

This is because Python does not expand automatically `~`. You can just replace it with your home directory. Or you can find the path in the pypath logfile.

> 
> l will remove CellChatDB l think
> 
> At the end the aim of my work will be to see all the OmniPath database ( withe the interations for humans in a dataframe) how l can do that?

If that's your final aim, maybe it's more suitable for you to use the web service. You can use the Python client https://github.com/saezlab/omnipath/ or the R client https://github.com/saezlab/OmnipathR and easily retrieve data frames from the server.

> 
> l have this dataframe bu i think they are missing some data?
> ![Capture](https://user-images.githubusercontent.com/79277563/114189947-0f1ba900-994b-11eb-8af8-5831c79299fe.PNG)

Yes, you already have an interactions data frame, I guess you loaded the `pypath.resources.network.pathway` dataset. You can load further datasets according to your needs, for example, `enzyme_substrate`, `ligand_receptor`, `pathway_noref`. For example:

```
from pypath.core import network
from pypath.resources import network as netres
n = network.Network(netres.pathway)
n.load(netres.pathway_noref)
n.load(netres.enzyme_substrate)
n.make_df()
n.df
```

> 
> thank in advance

**Comment by jeremyEudaric** [comment] 2021-04-09 15:55
Thank you
how works the python client? l wondering that because in download omnipath and did pypath.inputs but l dont see anything where l can see they data? Could you explain to me  the procédure to see all the OmniPath database ( withe the interations for humans in a dataframe) 

Thank you for your time and your help

**Comment by deeenes** [comment] 2021-04-09 17:49
The Python client works by downloading data from the web service at https://omnipathdb.org/. You can install the Python client by `pip`:

```
pip install omnipath
```

Or from git:

```
pip install git+https://github.com/saezlab/omnipath.git
```

Then you can use the various classes in `omnipath.interactions` to query the web server, and you can provide further parameters to customize the queries. For example:

```
import omnipath
i = omnipath.interactions.PostTranslational.get()
```
```

**Comment by deeenes** [comment] 2021-04-13 20:30
I am closing this due to lack of specific question and inactivity in the past 4 days. I hope we could answer some of your questions, and feel free to open a new issue if you have more to ask.

**Closed by deeenes** 2021-04-13 20:30 UTC
Labels: help wanted, incomplete

**Comment by slobentanzer** [comment] 2021-12-03 10:09
![](https://github.trello.services/images/mini-trello-icon.png) [pypath collab: how do we manage collaborators from outside the saezlab github organisation?](https://trello.com/c/lNZGpIFu/63-pypath-collab-how-do-we-manage-collaborators-from-outside-the-saezlab-github-organisation)
