### ISSUE TITLE
load_resources fails for Reactome data

### ISSUE THREAD

**Issue by caleb-lindgren** [saezlab/pypath#142] opened 2020-05-07 23:50 UTC
**Describe the bug**
I'm trying to find a way to work with Reactome pathway diagrams as iGraph objects, so I can make custom visualizations of them. I don't want to use Cytoscape, and your tool was the only one I could find that converts Reactome data to iGraph.

However, when I try to load the data from Reactome, pypath says "`reactome_interactions`: Could not find file or input function or failed preprocessing."

Additionally, I'm not sure if I'm loading the correct data from Reactome. There seemed to be several options, and I wasn't sure which one to use. What I want is the pathway diagrams you can see in their Pathway browser and can download as SBML/SBGN/BioPAX files.

I also tried this with the legacy version, and it failed in the same way. Either way, it looks like I may have to use the legacy version if I want iGraph objects, according to #128 .

**To Reproduce**
1. Install pypath
2. Execute these commands:
```
>>> from pypath.core import network
>>> from pypath.resources import network as netres
>>> from pypath.resources import data_formats
>>> n = network.Network()
>>> n.load_resources({"reactome": data_formats.reaction_misc["reactome"]})
```

**Expected behavior**
Reactome data would be loaded.

**Traceback**
[2020-05-07 17:27:27] [network] `reactome_interactions`: Could not find file or input function
or failed preprocessing.

**Log file**
[2020-05-07 17:26:36] Welcome!
[2020-05-07 17:26:36] Logger started, logging into `/home/caleb/pypath_log/pypath-l3gmd.log`.
[2020-05-07 17:26:36] Session `l3gmd` started.
[2020-05-07 17:26:36] [pypath]
    - session ID: `l3gmd`
    - working directory: `/home/caleb`
    - logfile: `/home/caleb/pypath_log/pypath-l3gmd.log`
    - pypath version: 0.10.6
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `HI-III` in set `interaction_deprecated`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `Vidal HI-III` in set `interaction_deprecated`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `HI-III` in set `interaction_deprecated`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `HumanSignalingNetwork` in set `interaction_deprecated`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `Negatome` in set `negative`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `SignaLink2` in set `obsolate`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `NCI-PID` in set `obsolate`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `Laudanna-effects` in set `pathway_bad`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `Laudanna-directions` in set `pathway_bad`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `PathwayCommons` in set `pathwaycommons`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `PathwayCommons` in set `pathwaycommons1`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `Reactome` in set `reactome_pc`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `SIGNOR` in set `small_molecule_protein`.
[2020-05-07 17:26:37] [network_resources] Could not find data model for resource `ORegAnno` in set `transcription_deprecated`.
[2020-05-07 17:27:12] [network] Creating network object.
[2020-05-07 17:27:24] [network] Loading network data from resource `Reactome`.
[2020-05-07 17:27:24] [network] Reading network data from `Reactome`.
[2020-05-07 17:27:24] [network] Expanding complexes for `Reactome`: False
[2020-05-07 17:27:27] [inputs] Selecting input method (step 1): module `reactome_interactions`, method `None`.
[2020-05-07 17:27:27] [inputs] Selecting input method (step 2): module `pypath.inputs.main`, method `reactome_interactions`.
[2020-05-07 17:27:27] [inputs] Importing module `pypath.inputs.main`.
[2020-05-07 17:27:27] [network] Retrieving data by method `reactome_interactions` of the pypath.inputs module...
[2020-05-07 17:27:27] [network] Error in method `reactome_interactions` of the pypath.inputs module. Skipping to next resource. See below the traceback.
[2020-05-07 17:27:27] [network] ("name 'raw_input' is not defined",)
[2020-05-07 17:27:27] [network] Failed handling exception.
[2020-05-07 17:27:27] [network] ("name 'traceback' is not defined",)
[2020-05-07 17:27:27] [network] `reactome_interactions`: Could not find file or input function or failed preprocessing.
[2020-05-07 17:27:27] [network] Loops allowed for resource `Reactome`: True
[2020-05-07 17:27:27] [network] Adding preprocessed edge list to existing network.
[2020-05-07 17:27:27] [network] _add_edge_list(): No data, nothing to do.
[2020-05-07 17:27:27] [network] Checking organisms. 0 nodes and 0 interactions before.
[2020-05-07 17:27:27] [network] Finished checking organisms. 0 nodes have been removed, 0 nodes and 0 interactions remained.
[2020-05-07 17:27:27] [network] Removing zero degree nodes. 0 nodes and 0 interactions before.
[2020-05-07 17:27:27] [network] Finished removing zero degree nodes. 0 nodes have been removed, 0 nodes and 0 interactions remained.
[2020-05-07 17:27:27] [network] Completed: loading network data from resource `Reactome`.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.7.7
 - Pypath version: 0.10.6

**Comment by deeenes** [comment] 2020-05-08 02:42
Hi, 

The input definition you tried uses our BioPax parser in `pypath.utils.pyreact`. This parser supposed to work well, I am not sure about the conversion of reactions to graph edges, I haven't even tried it in the past 4 years. In this conversion we apply the rules described by PathwayCommons, and the default settings in `pypath` are very stringent, unless you change these you will end up with very few interactions.

There is an easier alternative, I just tried and it works. It downloads the already converted interactions from PathwayCommons. Also to get an `igraph` object you need to use the legacy `PyPath` class, because the `to_igraph` method in `pypath.core.network.Network` is not implemented yet.

```
from pypath.resources import network as netres
from pypath.legacy import main

pa = main.PyPath()
pa.load_resources(netres.reactome_pc)
```

You will end up with ~250k connections and ~10k proteins.

Best wishes,

Denes

**Comment by deeenes** [comment] 2020-05-08 02:44
Otherwise this issue reveals a number of small bugs which can be traced back to Py 2/3 compatibility (it was so long time ago I touched this part of the code!). I will fix these soon.

**Comment by caleb-lindgren** [comment] 2020-05-08 04:05
Awesome, thank you! I have one other question related to Reactome. I was able to load the network following your instructions, but I'm more interested in the individual diagrams like [this](https://reactome.org/PathwayBrowser/#/R-HSA-76005) that you can download from their website as SBML or BioPAX files. I want to visualize those individual diagrams, not the whole network all at once. Does your package have a way to do that? I was looking at the [pypath.dataio.reactome_sbml()](http://pypath.omnipathdb.org/reference.html#pypath.dataio.reactome_sbml) function in the legacy documentation, hoping that it could read SBML files, but it doesn't look like it.

**Comment by deeenes** [comment] 2020-05-08 13:54
I don't know about the `reactome_sbml` method, I think it's a really old one and we will remove it at some point. From Reactome we never processed the pathway annotations because it's a really large and deep ontology. From KEGG with pypath it's possible to reproduce individual pathway diagrams as networks because that's much easier: by `pypath.core.annot.KeggPathways` you are able to get the groups of proteins for each pathway and using `pypath.resources.network.pathway_noref['kegg']` you can get the network connections. Of course the network you can get independently from any resource(s) it does not need to be KEGG. And pathways are also available from SIGNOR, NetPath and SignaLink.

I also need to note that Reactome and other process description databases (KEGG, ACSN, WikiPathways, Panther, etc) are a bit out of scope for pypath because the difficulties with the conversion. pypath is mainly about networks i.e. activity flow type of databases which already represent the interactions as binary relationships.

**Comment by caleb-lindgren** [comment] 2020-05-08 15:33
Gotcha, that all makes sense. Yeah, I've been realizing that Reactome might need something more complex than an underlying iGraph object to represent the pathways. Thanks for letting me know about those other resources, I think they'd be helpful! I might look into COBRApy as well, for working with the more complex models. Thanks again!

I'm fine with closing this issue, but I don't know if you wanted to keep it open until you fixed those bugs you mentioned that you found. Either way is fine with me.

**Closed** 2020-08-12 01:15 UTC
Labels: bug
