### ISSUE TITLE
installation under python2

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#88] opened 2019-06-04 13:06 UTC
Dear Omnipath Developers,

I am installing pypath under Windows subsystem for Linux (windows10 – Ubuntu 18.04).
After separately installing all the softwares required for preinstallation (cairo, py(2,3)cairo, igraph, python(2,3)-igraph, graphviz, pygraphviz). I successfully install pypath(0.8.9) via pip3.

However, when running via pip, I got the following error message.  I guess I do not need pypath installed both under python3 and python2. However, it is not very clear from github whether incompatibility remains in Python3 or Python2.

Thank you in advance for your help!

Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/dist-packages (from requests>=2.18.4->chembl_webresource_client->pypath==0.8.9)
Collecting unittest2py3k (from unittest2six->chembl_webresource_client->pypath==0.8.9)
  Using cached https://files.pythonhosted.org/packages/4e/3d/d44421e8d828af1399c1509c196db92e2a58f3764b01a0ee928d7025d1ca/unittest2py3k-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xPdfUL/unittest2py3k/setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "unittest2/__init__.py", line 61, in <module>
        from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
      File "unittest2/case.py", line 539
        def assertAlmostEqual(self, first, second, *, places=None, msg=None,
                                                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xPdfUL/unittest2py3k/

**Comment by deeenes** [comment] 2019-06-04 14:26
Hi,

Sorry, indeed the text is not completely clear. Now we only develop and use pypath in Python 3. In theory it is Python 2 compatible, and apparently some people use it there, but for example me I tried only long time ago. The error is strange, I've never seen this. But as you wrote you finally managed to install, I think this issue is already pointless?

Best,

Denes

**Comment by Nic-Nic** [comment] 2019-06-04 14:29
This seems to be an error from `unittest2py3k` package, I got a similar error by trying `pip install unittest2py3k`. Despite this, I could not reproduce your error when installing PyPath with `pip2 install .` (when inside the `pypath/` directory), also `unittest2py3k` is not used anywhere inside PyPath. It rather seems to be from 
Do you have `unittest2` and `unittest2six` installed (you can check with `pip2 list`)? Which version is your `pip --version`?

**Comment by luli7** [comment] 2019-06-04 14:40
Hi Denes and Nic,

Thank you very much for your reply.
I will focus on using pypath under python3. 
my pip version is 9.0.1
indeed I do not have unittest2 and unittest2six. 
I successfully installed unittest2 but when use pip install unittest2six, I get very similar error message as when I install pypath:

Collecting unittest2six
Collecting unittest2py3k (from unittest2six)
  Using cached https://files.pythonhosted.org/packages/4e/3d/d44421e8d828af1399c1509c196db92e2a58f3764b01a0ee928d7025d1ca/unittest2py3k-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZvGM5L/unittest2py3k/setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "unittest2/__init__.py", line 61, in <module>
        from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
      File "unittest2/case.py", line 539
        def assertAlmostEqual(self, first, second, *, places=None, msg=None,
                                                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZvGM5L/unittest2py3k/

**Comment by Nic-Nic** [comment] 2019-06-04 14:48
But what is the exact output of `pip --version`? Is it using Python 2.X or 3.X? According to the [requirements of `unittest2six`](https://github.com/msabramo/unittest2six/blob/master/setup.py) `unittest2py3k` is only required when running the installation on Python 3 (which shouldn't be on this case).

**Comment by luli7** [comment] 2019-06-04 14:56
Hi Nic,
The output is:
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

yes I have unittest2py3k installed under pip3.

cheers
Lu

**Comment by Nic-Nic** [comment] 2019-06-04 17:21
Then this shouldn't be happening... If installing `unittest2six` under Python 2.7 then it shouldn't attempt to install `unittest2py3k`... After some searching, it seems the error is coming from this last package. Best option I can think of is to [download it](https://files.pythonhosted.org/packages/4e/3d/d44421e8d828af1399c1509c196db92e2a58f3764b01a0ee928d7025d1ca/unittest2py3k-0.5.1.tar.gz) and remove the `*, ` in from the lines 539 and 578 in `unittest2py3k-0.5.1/unittest2/case.py` file and install it from source (`pip2 install .` inside the `unittest2py3k-0.5.1/` directory). Hopefully with this the requirement will be satisfied and `pip` will not try to install it from the PyPi.
Still, it's not clear to me why the `setup.py` of `unittest2six` tries to install it if it's in Python 2.7...

**Comment by Nic-Nic** [comment] 2019-06-07 13:04
Closing since issue is not directly related to PyPath

**Closed by Nic-Nic** 2019-06-07 13:04 UTC
Labels: help wanted
