### ISSUE TITLE
can not import main from pyapth.legacy

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#135] opened 2020-02-21 09:56 UTC
Hi,
Thank you very much for closing bug report #134.
Prior to my report, I have tried both from pypath import main or from pypath.legacy import main.
I have obtained the same error message: AttributeError: module 'pypath' has no attribute 'resources'.

I have read Denes' reply to #132. It does not solve my problem. Maybe I have missed anything?

Thank you for your help
Best regards
Lu

**Comment by Nic-Nic** [comment] 2020-02-21 10:00
Can you please provide which version are you using, a reproducible example and a complete traceback? Otherwise we can't help you much.
Using the current `pypath` version in the `master` branch I can run `from pypath.legacy import main` without problems.

**Comment by luli7** [comment] 2020-02-21 10:06
Hi Nic,
Apologise for forgetting to mention the pypath version.
I am using pypath 0.10.5 from master, I have also tried pypath 0.10.4 from dev.
I am having python 3.6.7, GCC 8.2.0
I am also running these under Ubuntu 18.04.2 LTS

Hope these provide enough information?
Thank you very much in advance
Lu

**Comment by luli7** [comment] 2020-02-21 10:12
sorry I forgot to add the "complete trace back"
if you want I can sent the log file as well.

        - pypath version: 0.10.5
>>> from pypath.legacy import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/legacy/main.py", line 109, in <module>
    import pypath.resources.data_formats as data_formats
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/resources/__init__.py", line 22, in <module>
    import pypath.resources.controller as _controller_mod
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/resources/controller.py", line 31, in <module>
    import pypath.internals.resource as resource_base
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/internals/resource.py", line 34, in <module>
    import pypath.inputs.main as dataio
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/inputs/main.py", line 109, in <module>
    import pypath.utils.mapping as mapping
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/utils/mapping.py", line 60, in <module>
    import pypath.resources.urls as urls
AttributeError: module 'pypath' has no attribute 'resources'

**Comment by ntung** [comment] 2020-02-21 10:19
I would say
```
import pypath.resources.data_formats as data_formats
from pypath.legacy import main
import pypath.share.settings as settings
```
works fine to me.
I am fixing tests and will commit shortly.

Cheers,
Tung

**Comment by luli7** [comment] 2020-02-21 10:27
Hi Tung,
Thank you very much for jumping in to help!
Nope, I still have the same error message.
I also tried to directly import resources from pypath, it also fails.
...
>>> import pypath.resources.data_formats as data_formats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/resources/__init__.py", line 22, in <module>
    import pypath.resources.controller as _controller_mod
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/resources/controller.py", line 31, in <module>
    import pypath.internals.resource as resource_base
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/internals/resource.py", line 34, in <module>
    import pypath.inputs.main as dataio
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/inputs/main.py", line 109, in <module>
    import pypath.utils.mapping as mapping
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/utils/mapping.py", line 60, in <module>
    import pypath.resources.urls as urls
AttributeError: module 'pypath' has no attribute 'resources'

**Comment by ntung** [comment] 2020-02-21 10:36
> Hi Tung,
> Thank you very much for jumping in to help!
With my pleasure!

> Nope, I still have the same error message.
> I also tried to directly import resources from pypath, it also fails.
> ...
> 
> > > > import pypath.resources.data_formats as data_formats
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/luli7/.local/lib/python3.6/site-packages/pypath/resources/**init**.py", line 22, in 
> > > > import pypath.resources.controller as _controller_mod
> > > > File "/home/luli7/.local/lib/python3.6/site-packages/pypath/resources/controller.py", line 31, in 
> > > > import pypath.internals.resource as resource_base
> > > > File "/home/luli7/.local/lib/python3.6/site-packages/pypath/internals/resource.py", line 34, in 
> > > > import pypath.inputs.main as dataio
> > > > File "/home/luli7/.local/lib/python3.6/site-packages/pypath/inputs/main.py", line 109, in 
> > > > import pypath.utils.mapping as mapping
> > > > File "/home/luli7/.local/lib/python3.6/site-packages/pypath/utils/mapping.py", line 60, in 
> > > > import pypath.resources.urls as urls
> > > > AttributeError: module 'pypath' has no attribute 'resources'

I am working on the `dev` branch as well. It works fine to me when inserting this import `import pypath.resources.urls as urls`. Did you pull the latest commits from the official repository? I guess @deeenes's latest commits will fix this problem.

Python on my machine is 3.7.6_1.

Cheers,
Tung

**Comment by deeenes** [comment] 2020-02-21 11:46
Hi Lu,

At this moment `dev` and `master` should be the same because we just merged everything.

From your traceback it's clear you have a version installed after the module reorganization (`0.10`).

I think this issue is very similar to one of your former issues, it is an import loop which somehow does not cause problem in our environments but your Python apparently resolves import dependencies by a different logic.

Please give me a little time and maybe I will find out.

Thanks for reporting this, maybe other people have the same issue and in our environments we just don't realize.

Best,

Denes

**Comment by luli7** [comment] 2020-02-21 11:50
Hi Denes,

Thank you very much for your reply.

I have now upgrade my python (from 3.6 to 3.7, following one comment from git), which made things worse… the problem comes from pycurl, which does not seem to support 3.7…

I will either compile pycurl manually or go back to python 3.6

Thank you
Lu

**Comment by deeenes** [comment] 2020-02-21 12:12
Hi Lu,

Upgrading Python is a good approach as they really ship nice new features in every major release.
But why not `3.8.1` as that's the current stable release?

Probably you are aware that with each new Python major version you need to reinstall all your modules by pip (except if the OS package manager does it for you).
I am not aware `pycurl` not supporting `3.7+`, I use it without any issue in all versions from `2.6` to `3.8`.

Meanwhile I reproduced your `module 'pypath' has no attribute 'resources'` issue in `3.6`, now I am resolving the import dependencies. Will come back to you soon.

Best,

Denes

**Comment by ntung** [comment] 2020-02-21 12:15
> Hi Denes, Thank you very much for your reply. I have now upgrade my python (from 3.6 to 3.7, following one comment from git), which made things worse… the problem comes from pycurl, which does not seem to support 3.7… I will either compile pycurl manually or go back to python 3.6
Hi @luli7 

I have encountered the problem with `pycurl`. Please doing as I described below will help you solve problem and keep playing with Python 3.7

As mentioned in README.rst file, you can resolve `pycurl` by reading instructions on the link: https://cscheng.info/2018/01/26/installing-pycurl-on-macos-high-sierra.html
I am pretty sure it should work for you.

Good luck!
Tung

**Closed** 2020-02-21 13:07 UTC
Labels: bug

**Comment by deeenes** [comment] 2020-02-21 13:18
Hi Lu,

Just to confirm: your issues were related to the behaviour of the import system in Py 3.6
Apparently the import system became much smarter since then, and for us it's good to be aware and I will try to test imports in `3.6` as many people still uses this version.

Please let me know if now it works for you.

Best,

Denes

**Comment by luli7** [comment] 2020-02-21 13:36
Hi Denes, Tung and Nic,

Thank you all for your timely help!
I confirm that the import is working under python 3.6.
I will upgrade my python and see whether I can get pycurl work under 3.7 or 3.8 (Thanks Tung for the link!!).

Thank you again, and wish you all a fantastic weekend!
Best regards
Lu
